org: d4vidmanu
service: api-s3

provider:
  name: aws
  runtime: python3.12
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::248552829072:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda

  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda

  # Nueva función para crear un bucket
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true
          integration: lambda

  # Nueva función para crear un "directorio" en un bucket
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/crear-directorio
          method: post
          cors: true
          integration: lambda

  # Nueva función para subir un archivo a un bucket existente en un directorio específico
  subir_archivo:
    handler: subir_archivo.lambda_handler
    events:
      - http:
          path: /s3/subir-archivo
          method: post
          cors: true
          integration: lambda
